// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de":    &dictionary{index: deIndex, data: deData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Open source equipment tracking software": 0,
	"Pricing":    3,
	"Quickstart": 2,
	"Simple equipment tracking. No lock-in. Self-host with a single Docker command.": 1,
}

var deIndex = []uint32{ // 5 elements
	0x00000000, 0x0000002b, 0x00000084, 0x00000091,
	0x00000098,
} // Size: 44 bytes

const deData string = "" + // Size: 152 bytes
	"\x02Open-Source-Software zur Geräteverwaltung\x02Einfache Geräteverwaltu" +
	"ng. Kein Lock-in. Self-Hosting mit einem einzigen Docker-Befehl.\x02Schn" +
	"ellstart\x02Preise"

var en_USIndex = []uint32{ // 5 elements
	0x00000000, 0x00000028, 0x00000077, 0x00000082,
	0x0000008a,
} // Size: 44 bytes

const en_USData string = "" + // Size: 138 bytes
	"\x02Open source equipment tracking software\x02Simple equipment tracking" +
	". No lock-in. Self-host with a single Docker command.\x02Quickstart\x02P" +
	"ricing"

	// Total table size 378 bytes (0KiB); checksum: CE4DDA2C
